 # Copyright (c) 2022, anonymous.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  vatex_caption_audio: # name of the dataset builder
    data_dir: $/home/abrimont/partage/mllm-video-captioner/lavis/datasets/
    data_type: videos # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/vatex/cap_train.json
          storage: /home/abrimont/partage/mllm-video-captioner/lavis/datasets/vatex/annotations/train_clean.json
        val:
          url: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/vatex/cap_val.json
          storage: /home/abrimont/partage/mllm-video-captioner/lavis/datasets/vatex/annotations/val_clean_filtered.json
        test:
          url: https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/vatex/cap_private_test.json
          storage: /home/abrimont/partage/mllm-video-captioner/lavis/datasets/vatex/annotations/test_clean_filtered.json
      videos:
        storage: /home/abrimont/partage/VALOR/datasets/vatex/raw_videos